Changing return type and count type in tty0tty_write to be compatible with new kernal and using udevadm to reload udev
lcgamboa/tty0tty pull request #20
Opened 2024-01-15 10:18 UTC by kapilpokhrel

2024-01-15 13:26 UTC, lcgamboa requested changes
This code doesn´t compile in kernel 6.5.13. You need to embrace your code with : 
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 6, 0)
#endif
```
Take a look at https://github.com/lcgamboa/tty0tty/issues/17#issuecomment-1890988789 issue.

2024-01-15 13:29 UTC, lcgamboa requested changes
Sorry, this commit is ok. There is no need for modification.  My previous observations are wrong.

2024-01-16 03:34 UTC, kapilpokhrel commented
Ok, I have only made the change to account for the kernel version

2024-01-16 14:08 UTC, lcgamboa approved these changes

2024-01-16 14:09 UTC, merged