Fix building with 5.15
lcgamboa/tty0tty pull request #7
Opened 2021-11-05 09:11 UTC by jjguti

2021-11-05 13:20 UTC, lcgamboa requested changes

2021-11-05 13:20 UTC, lcgamboa commented on module/tty0tty.c
> +#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
Please change to `LINUX_VERSION_CODE >= KERNEL_VERSION(5, 15, 0)` to work with previous versions.

2021-11-08 10:25 UTC, jjguti commented on module/tty0tty.c
> +#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
This change works both with 5.15 and previous (tested). This if is to define aliases for older versions of the kernel to the new functions while the changes below call the new functions.

2021-11-08 13:58 UTC, lcgamboa commented on module/tty0tty.c
> +#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
It work, but emit redefined warnings. That's what confused me. 

```
  CC [M]  /tmp/tty0tty/module/tty0tty.o
/tmp/tty0tty/module/tty0tty.c:55: warning: "tty_alloc_driver" redefined
   55 | #define tty_alloc_driver(x, y) alloc_tty_driver(x)
      | 
In file included from /usr/src/linux-headers-5.14.0-2-common/include/linux/tty.h:9,
                 from /tmp/tty0tty/module/tty0tty.c:36:
/usr/src/linux-headers-5.14.0-2-common/include/linux/tty_driver.h:339: note: this is the location of the previous definition
```

2021-11-08 13:59 UTC, merged